/* ANIMA app.js parte 1: datos + base */
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const BIOMES={selva:{n:"SELVA",d:"hierba meciendose · clic para esporas"},cielo:{n:"CIELO",d:"hojas con la brisa · mueve el mouse"},laguna:{n:"LAGUNA",d:"ondas y nenufares · clic para ondas"},oceano:{n:"OCEANO",d:"burbujas ascendentes · clic para chorro"},sabana:{n:"SABANA",d:"brasas nocturnas · clic para chispas"}};
const SPECIES={
jaguar:{n:"Jaguar",s:"Panthera onca",g:"Mamifero - Selva",img:"https://images.unsplash.com/photo-1561731216-c3a4d99437d5?q=80&w=800&auto=format&fit=crop",d:"Felino americano de mordida extrema. Nada y trepa.",grupo:"Mamifero",habitat:"Selva",alim:"Carnivoro",resp:"Pulmonar",ext:"4 patas",temp:"Endotermo"},
aguila:{n:"Aguila calva",s:"Haliaeetus leucocephalus",g:"Ave - Montanas",img:"https://images.unsplash.com/photo-1611689342806-0863700ce1e4?q=80&w=800&auto=format&fit=crop",d:"Rapaz de vision 20/2 y sacos aereos.",grupo:"Ave",habitat:"Bosques",alim:"Carnivoro",resp:"Pulmonar + sacos",ext:"2 + alas",temp:"Endotermo"},
delfin:{n:"Delfin",s:"Tursiops truncatus",g:"Mamifero - Oceano",img:"https://images.unsplash.com/photo-1607153333879-c174d265f1d2?q=80&w=800&auto=format&fit=crop",d:"Ecolocaliza. Duerme con medio cerebro despierto.",grupo:"Mamifero",habitat:"Oceano",alim:"Carnivoro",resp:"Pulmonar",ext:"Aletas",temp:"Endotermo"},
elefante:{n:"Elefante",s:"Loxodonta africana",g:"Mamifero - Sabana",img:"https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?q=80&w=800&auto=format&fit=crop",d:"Trompa de 40 mil musculos.",grupo:"Mamifero",habitat:"Sabana",alim:"Herbivoro",resp:"Pulmonar",ext:"4 patas",temp:"Endotermo"},
tortuga:{n:"Tortuga marina",s:"Chelonia mydas",g:"Reptil - Arrecife",img:"https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?q=80&w=800&auto=format&fit=crop",d:"Caparazon fusionado a su columna.",grupo:"Reptil",habitat:"Arrecife",alim:"Omnivoro",resp:"Pulmonar",ext:"4 aletas",temp:"Ectotermo"},
rana:{n:"Rana dardo",s:"Dendrobates tinctorius",g:"Anfibio - Selva",img:"https://images.unsplash.com/photo-1496070242169-b672c576566b?q=80&w=800&auto=format&fit=crop",d:"Respira por la piel.",grupo:"Anfibio",habitat:"Selva humeda",alim:"Insectivoro",resp:"Cutanea",ext:"4 patas",temp:"Ectotermo"},
lobo:{n:"Lobo gris",s:"Canis lupus",g:"Mamifero - Bosque",img:"https://images.unsplash.com/photo-1547407139-3c921a66005c?q=80&w=800&auto=format&fit=crop",d:"Olfato prodigioso y caza en manada.",grupo:"Mamifero",habitat:"Boreal",alim:"Carnivoro",resp:"Pulmonar",ext:"4 patas",temp:"Endotermo"},
camaleon:{n:"Camaleon",s:"Chamaeleo calyptratus",g:"Reptil - Selva seca",img:"https://images.unsplash.com/photo-1504457047772-27faf1c00561?q=80&w=800&auto=format&fit=crop",d:"Ojos 360 y lengua balistica.",grupo:"Reptil",habitat:"Selva seca",alim:"Insectivoro",resp:"Pulmonar",ext:"4 patas",temp:"Ectotermo"},
tigre:{n:"Tigre",s:"Panthera tigris",g:"Mamifero - Selva",img:"https://images.unsplash.com/photo-1534759846116-5799c33ce22a?q=80&w=800&auto=format&fit=crop",d:"Rayas unicas. Salto de 10 metros.",grupo:"Mamifero",habitat:"Selva asiatica",alim:"Carnivoro",resp:"Pulmonar",ext:"4 patas",temp:"Endotermo"},
buho:{n:"Buho real",s:"Bubo bubo",g:"Ave - Nocturno",img:"https://images.unsplash.com/photo-1552728089-57bdde30beb3?q=80&w=800&auto=format&fit=crop",d:"Cuello 270 grados. Vuelo silencioso.",grupo:"Ave",habitat:"Bosque",alim:"Carnivoro",resp:"Pulmonar + sacos",ext:"2 + alas",temp:"Endotermo"},
tiburon:{n:"Tiburon blanco",s:"Carcharodon carcharias",g:"Pez - Oceano",img:"https://images.unsplash.com/photo-1544552866-d3ed42536cfd?q=80&w=800&auto=format&fit=crop",d:"Electrorrecepcion y 300 dientes.",grupo:"Acuatico",habitat:"Oceano",alim:"Carnivoro",resp:"Branquial",ext:"Aletas",temp:"Ectotermo"},
cocodrilo:{n:"Cocodrilo",s:"Crocodylus niloticus",g:"Reptil - Rio",img:"https://images.unsplash.com/photo-1591025207163-942350e47db2?q=80&w=800&auto=format&fit=crop",d:"Mordida 3700 PSI. Fosil viviente.",grupo:"Reptil",habitat:"Rios",alim:"Carnivoro",resp:"Pulmonar",ext:"4 patas",temp:"Ectotermo"},
oso:{n:"Oso pardo",s:"Ursus arctos",g:"Mamifero - Boreal",img:"https://images.unsplash.com/photo-1547721064-da6cfb341d50?q=80&w=800&auto=format&fit=crop",d:"Hiberna 7 meses. Olfato extremo.",grupo:"Mamifero",habitat:"Montana",alim:"Omnivoro",resp:"Pulmonar",ext:"4 patas",temp:"Endotermo"},
colibri:{n:"Colibri",s:"Archilochus colubris",g:"Ave - Jardin",img:"https://images.unsplash.com/photo-1444464666168-49d633b86797?q=80&w=800&auto=format&fit=crop",d:"80 aleteos/s. Vuela hacia atras.",grupo:"Ave",habitat:"Jardines",alim:"Nectarivoro",resp:"Pulmonar + sacos",ext:"2 + alas",temp:"Endotermo"},
pulpo:{n:"Pulpo",s:"Octopus vulgaris",g:"Molusco - Arrecife",img:"https://images.unsplash.com/photo-1546026423-cc4642628d2b?q=80&w=800&auto=format&fit=crop",d:"3 corazones y 9 cerebros.",grupo:"Acuatico",habitat:"Arrecife",alim:"Carnivoro",resp:"Branquial",ext:"8 brazos",temp:"Ectotermo"},
ajolote:{n:"Ajolote",s:"Ambystoma mexicanum",g:"Anfibio - Lago",img:"https://images.unsplash.com/photo-1503656142023-618e7d1f435a?q=80&w=800&auto=format&fit=crop",d:"Regenera cerebro y corazon.",grupo:"Anfibio",habitat:"Lagos",alim:"Carnivoro",resp:"Branquial + cutanea",ext:"4 patas",temp:"Ectotermo"},
tucan:{n:"Tucan",s:"Ramphastos toco",g:"Ave - Dosel",img:"https://images.unsplash.com/photo-1555169062-013468b47731?q=80&w=800&auto=format&fit=crop",d:"Pico termorregulador gigante.",grupo:"Ave",habitat:"Dosel",alim:"Frugivoro",resp:"Pulmonar + sacos",ext:"2 + alas",temp:"Endotermo"}};
const SYSTEMS={
oseo:{n:"Sistema oseo",i:"fa-bone",d:"Estructura que sostiene y protege.",f:"Soporte y locomocion.",s:"Jaguar compacto, aguila neumatizada, tortuga con caparazon fusionado."},
muscular:{n:"Sistema muscular",i:"fa-dumbbell",d:"Mas de 600 musculos en movimiento.",f:"Movimiento y calor.",s:"Elefante trompa 40k, delfin motor caudal."},
respiratorio:{n:"Sistema respiratorio",i:"fa-lungs",d:"Pulmones, sacos aereos y piel.",f:"Intercambio de gases.",s:"Aguila sacos aereos, rana cutanea, delfin espiraculo."},
circulatorio:{n:"Sistema circulatorio",i:"fa-heart-pulse",d:"Corazones de 2 a 4 camaras.",f:"Transportar oxigeno.",s:"Mamiferos 4 camaras, reptiles 3."},
digestivo:{n:"Sistema digestivo",i:"fa-bowl-food",d:"De lengua balistica a fermentador.",f:"Digestion.",s:"Camaleon lengua 2x, lobo carnivoro, elefante herbivoro."},
nervioso:{n:"Sistema nervioso",i:"fa-brain",d:"Ecolocalizacion y memoria.",f:"Coordinacion.",s:"Delfin ecolocaliza, lobo olfato 100k."}};
const ANAT_LABEL={jaguar:"Jaguar",aguila:"Águila calva",delfin:"Delfín",elefante:"Elefante",tortuga:"Tortuga marina",rana:"Rana dardo",lobo:"Lobo gris",camaleon:"Camaleón",tigre:"Tigre",buho:"Búho real",tiburon:"Tiburón blanco",cocodrilo:"Cocodrilo",oso:"Oso pardo",colibri:"Colibrí",pulpo:"Pulpo",ajolote:"Ajolote",tucan:"Tucán"};
const ANATOMY={
jaguar:{spots:[{id:"craneo",n:"Cráneo y colmillos",x:"76%",y:"24%",d:"Cráneo corto y robusto que perfora caparazones.",f:["Mordida ~1500 PSI","Caninos anti-fractura","Agarre para arrastrar"]},{id:"ojos",n:"Ojos nocturnos",x:"48%",y:"36%",d:"Visión crepuscular con tapetum lucidum.",f:["Amplifica penumbra","Binocular para salto","Bigotes miden distancia"]},{id:"corazon",n:"Corazón sprinter",x:"55%",y:"50%",d:"Bomba de 4 cámaras para sprint y nado.",f:["+100 ppm en caza","Doble circulación","Recuperación rápida"]},{id:"garras",n:"Garras y almohadillas",x:"40%",y:"78%",d:"Garras retráctiles y pisada silenciosa.",f:["Siempre afiladas","Pisada silenciosa","Trepa y nada"]},{id:"pelaje",n:"Pelaje con rosetas",x:"62%",y:"62%",d:"Rosetas únicas que rompen su silueta.",f:["Camuflaje moteado","Patrón único","Protege en maleza"]}]},
aguila:{spots:[{id:"pico",n:"Pico ganchudo",x:"72%",y:"26%",d:"Pico para desgarrar con precisión.",f:["Corte eficiente","Crecimiento continuo","Narinas de altura"]},{id:"ojos",n:"Ojos telescópicos",x:"60%",y:"32%",d:"Visión 8x la humana.",f:["Dos fóveas por ojo","Detecta a 3 km","Membrana protectora"]},{id:"alas",n:"Alas planeadoras",x:"42%",y:"52%",d:"2 m para planear sin batir.",f:["Plumas con ranuras","Planeo térmico","Cola timón"]},{id:"garras",n:"Garras talón",x:"52%",y:"74%",d:"15 kg de presión.",f:["Talones curvos","Bloqueo automático","Antideslizantes"]},{id:"sacos",n:"Sacos aéreos",x:"58%",y:"60%",d:"Respiración de flujo continuo.",f:["9 sacos aéreos","Oxígeno al exhalar","Huesos ligeros"]}]},
delfin:{spots:[{id:"melon",n:"Melón sonar",x:"70%",y:"28%",d:"Enfoca clics de ecolocalización.",f:["Sonar alta frecuencia","Distingue materiales","Cientos de metros"]},{id:"espiraculo",n:"Espiráculo",x:"52%",y:"34%",d:"Válvula nasal superior.",f:["Abre en 0.3 s","Cierre hermético","90% intercambio"]},{id:"aleta",n:"Aletas",x:"48%",y:"58%",d:"Estabilizadores de precisión.",f:["Dorsal única","Giro y freno","Sin huella térmica"]},{id:"cola",n:"Aleta caudal",x:"28%",y:"62%",d:"Motor hasta 35 km/h.",f:["Movimiento vertical","Músculo potente","Larga distancia"]},{id:"cerebro",n:"Medio cerebro despierto",x:"62%",y:"42%",d:"Duerme con un hemisferio alerta.",f:["Vigilia parcial","Sueño consciente","Memoria social"]}]},
elefante:{spots:[{id:"trompa",n:"Trompa multiuso",x:"68%",y:"48%",d:"40 000 músculos: nariz y mano.",f:["Levanta 300 kg","Recoge una hoja","Huele agua a km"]},{id:"orejas",n:"Orejas radiador",x:"42%",y:"30%",d:"Disipan calor con capilares.",f:["2 m² superficie","Baja 2-3 °C","Venas únicas"]},{id:"colmillos",n:"Colmillos marfil",x:"60%",y:"58%",d:"Incisivos continuos.",f:["Cavan y descortezan","Defensa","Crecen siempre"]},{id:"piel",n:"Piel blindada",x:"48%",y:"66%",d:"2.5 cm pero sensible.",f:["Oye por vibración","Barro protector","Retiene agua"]},{id:"patas",n:"Patas de puntillas",x:"50%",y:"82%",d:"Cojín para 6 toneladas.",f:["Amortigua peso","Escucha por pies","Silenciosas"]}]},
tortuga:{spots:[{id:"caparazon",n:"Caparazón vivo",x:"50%",y:"52%",d:"Costillas y columna fusionadas en armadura.",f:["Espaldar + plastrón","Crece con el animal","Repara fracturas"]},{id:"aletas",n:"Aletas delanteras",x:"32%",y:"58%",d:"Alas marinas para volar bajo el agua.",f:["Migra 10 000 km","Propulsión eficiente","Uñas vestigiales"]},{id:"cabeza",n:"Cabeza y glándula sal",x:"70%",y:"30%",d:"Llora el exceso de sal.",f:["Glándulas lagrimales","Pico córneo","Brújula magnética"]},{id:"apnea",n:"Apnea prolongada",x:"56%",y:"62%",d:"Bucea horas con bradicardia.",f:["Baja a 10 ppm","Bucea 150 m","Ahorro extremo"]},{id:"piel",n:"Piel y escamas",x:"44%",y:"72%",d:"Escamas hidrodinámicas.",f:["Menos arrastre","Resiste arrecife","Toma sol"]}]},
rana:{spots:[{id:"piel",n:"Piel respirable",x:"52%",y:"58%",d:"Respira y bebe por la piel.",f:["Respiración cutánea","Alcaloides tóxicos","Color de aviso"]},{id:"ojos",n:"Ojos panorámicos",x:"66%",y:"28%",d:"Visión casi 360°.",f:["Hunde ojos al tragar","Detecta movimiento","Párpado transparente"]},{id:"lengua",n:"Lengua balística",x:"62%",y:"44%",d:"Más rápida que un parpadeo.",f:["Adhesivo reversible","Apunta en 3D","Recarga en ms"]},{id:"patas",n:"Patas de salto",x:"38%",y:"76%",d:"Salta 20 veces su cuerpo.",f:["Tendón catapulta","Discos adhesivos","Nada y trepa"]},{id:"timpano",n:"Tímpano externo",x:"58%",y:"34%",d:"Oye sin oído externo.",f:["Canto territorial","Ultra sensible","Vibración suelo"]}]},
lobo:{spots:[{id:"hocico",n:"Hocico olfativo",x:"70%",y:"36%",d:"200 M de receptores.",f:["100 000x humano","Rastrea a 2 km","Memoria de manada"]},{id:"orejas",n:"Orejas radar",x:"58%",y:"24%",d:"Triangulan sonidos.",f:["Giran 180°","Oye a 10 km","Señal visual"]},{id:"dientes",n:"Dentadura carnicera",x:"66%",y:"46%",d:"42 dientes corta-hueso.",f:["Tritura hueso","Caninos sujeción","Desgaste compensado"]},{id:"lomo",n:"Lomo corredor",x:"48%",y:"56%",d:"Trota 60 km por día.",f:["Trote 10 km/h","Sprint 60 km/h","Doble capa aislante"]},{id:"patas",n:"Pies raqueta",x:"42%",y:"80%",d:"Raquetas para nieve.",f:["Antideslizantes","Tracción en barro","Aúlla a 10 km"]}]},
camaleon:{spots:[{id:"ojos",n:"Ojos torreta 360°",x:"68%",y:"26%",d:"Ojos independientes con zoom.",f:["360° sin mover cabeza","Enfoque binocular","Párpado cónico"]},{id:"lengua",n:"Lengua 2x cuerpo",x:"62%",y:"46%",d:"Disparo en 0.07 s.",f:["Aceleración extrema","Punta ventosa","Colágeno elástico"]},{id:"piel",n:"Piel cromatófora",x:"48%",y:"58%",d:"Cambia color por luz y ánimo.",f:["Camuflaje activo","Señal social","Nanocristales"]},{id:"cola",n:"Cola prensil",x:"28%",y:"66%",d:"Quinta extremidad.",f:["Enrolla ramas","Equilibrio","Reserva grasa"]},{id:"patas",n:"Pies pinza",x:"44%",y:"80%",d:"Pinzas 2+3.",f:["Agarre alicate","Uñas curvas","Paso sigiloso"]}]},
tigre:{spots:[{id:"rayas",n:"Rayas únicas",x:"52%",y:"52%",d:"Código de barras propio.",f:["Patrón único","Rompe silueta","Reconoce crías"]},{id:"ojos",n:"Visión nocturna 6x",x:"66%",y:"28%",d:"Caza en penumbra.",f:["Pupila total","Bigotes 15 cm","Acecho total"]},{id:"zarpas",n:"Zarpas 10 m",x:"38%",y:"74%",d:"Salto récord + garras 10 cm.",f:["Salto horizontal","Nadador potente","Tumba búfalos"]},{id:"mandibula",n:"Mandíbula y colmillos",x:"62%",y:"42%",d:"Caninos de 9 cm.",f:["Muerde nuca","Arrastra 500 kg","Ruge a 3 km"]},{id:"cola",n:"Cola timón",x:"30%",y:"60%",d:"Equilibrio a toda velocidad.",f:["Contrapeso","Señal crías","Mide 1 m"]}]},
buho:{spots:[{id:"ojos",n:"Ojos tubulares",x:"62%",y:"30%",d:"100x más sensibles a la luz.",f:["Visión nocturna","Cabeza compensa","Disco facial parabólico"]},{id:"cuello",n:"Cuello 270°",x:"52%",y:"46%",d:"14 vértebras sin cortar sangre.",f:["Giro 270°","Arterias reserva","Caza sin moverse"]},{id:"alas",n:"Vuelo silencioso",x:"38%",y:"56%",d:"Flecos que anulan sonido.",f:["0 dB al planear","Borde serrado","Ataque inaudible"]},{id:"garras",n:"Garras nocturnas",x:"52%",y:"74%",d:"Perforan cráneos de ratón.",f:["Dedo reversible","Agarre total","Caza por oído"]},{id:"oidos",n:"Oídos asimétricos",x:"70%",y:"38%",d:"Un oído alto y otro bajo: 3D sonoro.",f:["Localiza a oscuras","Caza bajo nieve","Memoria auditiva"]}]},
tiburon:{spots:[{id:"hocico",n:"Ampollas de Lorenzini",x:"70%",y:"36%",d:"Detecta latidos eléctricos.",f:["5 nanovoltios","Caza enterrada","Brújula magnética"]},{id:"dientes",n:"300 dientes rotativos",x:"62%",y:"50%",d:"Cinta transportadora dental.",f:["300 en recambio","Renueva 2 semanas","Serrados"]},{id:"piel",n:"Piel dentículos",x:"48%",y:"58%",d:"Escamas-diente hidrodinámicas.",f:["-10% fricción","Anti-parásitos","Inspira neoprenos"]},{id:"aleta",n:"Cola heterocerca",x:"28%",y:"60%",d:"Empuje y sustentación.",f:["Crucero eficiente","Sprint 56 km/h","Sin vejiga"]},{id:"higado",n:"Hígado flotador",x:"55%",y:"64%",d:"Aceite escualeno que flota.",f:["25% del peso","Flota sin esfuerzo","Reserva energía"]}]},
cocodrilo:{spots:[{id:"mandibula",n:"Mordida 3700 PSI",x:"68%",y:"42%",d:"La más fuerte del reino animal.",f:["3700 PSI","Músculo aductor","Apertura débil"]},{id:"ojos",n:"Ojos periscopio",x:"58%",y:"28%",d:"Acecha 95% sumergido.",f:["Flotación perfecta","Membrana nocturna","Glándula sal"]},{id:"cola",n:"Cola propulsora",x:"30%",y:"60%",d:"Nada y hace death-roll.",f:["30 km/h","Giro mortal","Reserva grasa"]},{id:"piel",n:"Armadura osteodermo",x:"50%",y:"56%",d:"Placas óseas bajo piel.",f:["Anti-mordidas","Sensores ISOs","Termorregula"]},{id:"corazon",n:"Corazón con bypass",x:"55%",y:"64%",d:"Bucea 2 horas.",f:["Foramen Panizza","Apnea 2 h","Sangre eficiente"]}]},
oso:{spots:[{id:"hocico",n:"Olfato 7x perro",x:"68%",y:"40%",d:"Huele a 30 km.",f:["EpitHelio gigante","Memoria carroña","Ayuna 7 meses"]},{id:"garras",n:"Garras excavadoras",x:"42%",y:"74%",d:"10 cm para cavar y pescar.",f:["No retráctiles","Zarpazo 500 kg","Trepa joven"]},{id:"grasa",n:"Grasa + hibernación",x:"52%",y:"60%",d:"Vive de su grasa a 8 ppm.",f:["Pierde 40% peso","Sin orinar meses","Despierta musculado"]},{id:"lomo",n:"Joroba muscular",x:"48%",y:"50%",d:"Corre 55 km/h pese a 600 kg.",f:["Excava","Sprint pesado","Voltea rocas"]},{id:"pelaje",n:"Pelaje doble",x:"56%",y:"66%",d:"Aísla a -40°.",f:["Repele agua","Muda primaveral","Color variable"]}]},
colibri:{spots:[{id:"pico",n:"Pico sonda",x:"70%",y:"38%",d:"Calza en cada flor.",f:["Lengua que bombea","Polinizador clave","Memoria floral"]},{id:"alas",n:"Alas 80 Hz",x:"44%",y:"54%",d:"80 aleteos/s y reversa.",f:["Hombro 180°","Flota helicóptero","Único reversa"]},{id:"corazon",n:"Corazón 1200 ppm",x:"56%",y:"62%",d:"El más rápido proporcional.",f:["1200 en vuelo","Torpor ahorra 90%","Metabolismo extremo"]},{id:"ojos",n:"Visión UV",x:"60%",y:"28%",d:"Tetracromático + ultravioleta.",f:["4 conos","Detecta néctar UV","Guía floral"]},{id:"patas",n:"Patas mínimas",x:"50%",y:"78%",d:"Vive en el aire.",f:["Solo percha","Nido telaraña","Migra 800 km"]}]},
pulpo:{spots:[{id:"brazos",n:"8 brazos pensantes",x:"50%",y:"62%",d:"Cada brazo decide solo.",f:["2/3 neuronas fuera","Gusto y tacto","Regenera brazos"]},{id:"cerebro",n:"9 cerebros + 3 corazones",x:"58%",y:"36%",d:"Aprende observando.",f:["Resuelve puzzles","2 corazones paran","Memoria topográfica"]},{id:"pico",n:"Pico de loro",x:"62%",y:"50%",d:"Rompe cangrejos.",f:["Veneno paralizante","Perfora conchas","Pasa por 2 cm"]},{id:"piel",n:"Piel camaleónica",x:"44%",y:"56%",d:"Color y textura en 0.3 s.",f:["Cromatóforos","Imita rocas","Tinta + escape"]},{id:"sifon",n:"Sifón jet",x:"38%",y:"70%",d:"Chorro a 40 km/h.",f:["Escape explosivo","Dirige chorro","Branquias eficientes"]}]},
ajolote:{spots:[{id:"branquias",n:"Branquias plumosas",x:"62%",y:"30%",d:"6 penachos que respiran.",f:["Branquial + cutánea","Regenera branquias","Sensa agua"]},{id:"regen",n:"Regeneración total",x:"52%",y:"42%",d:"Regenera cerebro y corazón.",f:["Miembros perfectos","Sin cicatriz","Modelo médico"]},{id:"piel",n:"Piel neoténica",x:"48%",y:"60%",d:"Adulto siempre larva.",f:["Neotenia","Respira por piel","Bioindicador"]},{id:"cola",n:"Cola nadadora",x:"30%",y:"64%",d:"Ondula en lagos.",f:["Nado ondulante","Reserva energía","Regenerable"]},{id:"ojos",n:"Ojos simples",x:"66%",y:"36%",d:"Ve poco, huele mucho.",f:["Lagos turbios","Línea lateral","Olfato guía"]}]},
tucan:{spots:[{id:"pico",n:"Pico ligero 20 cm",x:"70%",y:"38%",d:"Hueco que regula calor.",f:["Espuma ósea","Radiador ajustable","Alcanza sin moverse"]},{id:"alas",n:"Alas de dosel",x:"42%",y:"54%",d:"Vuelo ondulante corto.",f:["Maniobra selva","Salta ramas","Cola timón"]},{id:"ojos",n:"Anillo azul",x:"60%",y:"28%",d:"Comunica estado.",f:["Señal social","Visión precisa","Expresivo"]},{id:"patas",n:"Pies 2+2",x:"50%",y:"78%",d:"Agarre de dosel.",f:["Escala vertical","Nido en huecos","Salto eficiente"]},{id:"pecho",n:"Pechera contraste",x:"55%",y:"62%",d:"Señal en dosel.",f:["Reconocimiento","Camuflaje luz","Muda anual"]}]}
};
const ANAT={
jaguar:{t:"Jaguar — Panthera onca",x:"Mamifero hipercarnivoro compacto, mordida que perfora caparazones.",img:"https://images.unsplash.com/photo-1561731216-c3a4d99437d5?q=80&w=600&auto=format&fit=crop",bars:[["Fuerza",95],["Vision",80],["Olfato",70],["Oido",75]],e:"Craneo corto y caninos gruesos. Almohadillas silenciosas. Corazon 4 camaras de sprinter."},
aguila:{t:"Aguila — Haliaeetus leucocephalus",x:"Rapaz de vuelo planeado y vista telescopica.",img:"https://images.unsplash.com/photo-1611689342806-0863700ce1e4?q=80&w=600&auto=format&fit=crop",bars:[["Vision",100],["Vuelo",95],["Olfato",30],["Oido",60]],e:"Huesos neumaticos huecos. Sacos aereos de doble flujo. Garras de 15 kg de presion."},
delfin:{t:"Delfin — Tursiops truncatus",x:"Mamifero marino con sonar biologico.",img:"https://images.unsplash.com/photo-1607153333879-c174d265f1d2?q=80&w=600&auto=format&fit=crop",bars:[["Sonar",100],["Nado",95],["Vision",50],["Oido",100]],e:"Melon frontal que enfoca clics. Espiraculo con valvula. Sueno unihemisferico."},
tortuga:{t:"Tortuga — Chelonia mydas",x:"Reptil marino con armadura viva fusionada.",img:"https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?q=80&w=600&auto=format&fit=crop",bars:[["Blindaje",100],["Nado",85],["Vision",60],["Olfato",70]],e:"Caparazon = costillas + columna fusionadas. Glandulas de sal. Magnetorrecepcion."},
rana:{t:"Rana — Dendrobates tinctorius",x:"Anfibio de piel permeable y aviso toxico.",img:"https://images.unsplash.com/photo-1496070242169-b672c576566b?q=80&w=600&auto=format&fit=crop",bars:[["Salto",90],["Piel",100],["Vision",70],["Oido",65]],e:"Respiracion cutanea. Alcaloides en la piel. Lengua pegajosa de 360 grados."},
camaleon:{t:"Camaleon — Chamaeleo calyptratus",x:"Reptil de ojos torreta y lengua balistica.",img:"https://images.unsplash.com/photo-1504457047772-27faf1c00561?q=80&w=600&auto=format&fit=crop",bars:[["Vision",100],["Lengua",100],["Camuflaje",95],["Velocidad",40]],e:"Ojos 360 independientes. Lengua 2x su cuerpo en 0.07 s. Pies zigodactilos."},
lobo:{t:"Lobo gris — Canis lupus",x:"Cazador social de manada con resistencia extrema.",img:"https://images.unsplash.com/photo-1547407139-3c921a66005c?q=80&w=600&auto=format&fit=crop",bars:[["Olfato",100],["Resistencia",95],["Oido",90],["Fuerza",85]],e:"200 M de receptores olfativos. Trota 60 km por dia. Aullido que une la manada a 10 km."},
tigre:{t:"Tigre — Panthera tigris",x:"Felino gigante solitario de salto prodigioso.",img:"https://images.unsplash.com/photo-1534759846116-5799c33ce22a?q=80&w=600&auto=format&fit=crop",bars:[["Fuerza",100],["Salto",95],["Vision",85],["Nado",80]],e:"Rayas unicas como huella. Salto de 10 m. Caninos de 9 cm para morder nuca."},
buho:{t:"Buho real — Bubo bubo",x:"Rapaz nocturna de vuelo silencioso.",img:"https://images.unsplash.com/photo-1552728089-57bdde30beb3?q=80&w=600&auto=format&fit=crop",bars:[["Vision",100],["Oido",100],["Sigilo",100],["Giro",95]],e:"Cuello de 270 grados con arterias de reserva. Oidos asimetricos para 3D sonoro."},
tiburon:{t:"Tiburon blanco — Carcharodon carcharias",x:"Depredador electrico con 300 dientes.",img:"https://images.unsplash.com/photo-1544552866-d3ed42536cfd?q=80&w=600&auto=format&fit=crop",bars:[["Mordida",100],["Electrico",100],["Nado",90],["Olfato",95]],e:"Ampollas de Lorenzini que detectan latidos. Higado de escualeno que flota."},
cocodrilo:{t:"Cocodrilo — Crocodylus niloticus",x:"Blindado de mordida record y apnea de 2 horas.",img:"https://images.unsplash.com/photo-1602053040316-5b1a1d2e5b4c?q=80&w=600&auto=format&fit=crop",bars:[["Mordida",100],["Blindaje",100],["Apnea",95],["Acecho",95]],e:"Mordida de 3700 PSI. Corazon con bypass de Panizza. Sensores ISOs en la piel."},
elefante:{t:"Elefante — Loxodonta africana",x:"Gigante inteligente de trompa multiuso.",img:"https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?q=80&w=600&auto=format&fit=crop",bars:[["Fuerza",100],["Olfato",95],["Memoria",100],["Oido",85]],e:"Trompa de 40 000 musculos. Orejas radiador. Se comunica por vibracion sismica."},
oso:{t:"Oso pardo — Ursus arctos",x:"Omnivoro que hiberna 7 meses.",img:"https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?q=80&w=600&auto=format&fit=crop",bars:[["Fuerza",100],["Olfato",100],["Resistencia",90],["Hibernacion",100]],e:"Baja a 8 ppm en hibernacion. Joroba muscular para excavar. Garras de 10 cm."},
colibri:{t:"Colibri — Colibri thalassinus",x:"Helicoptero vivo de 80 aleteos por segundo.",img:"https://images.unsplash.com/photo-1501706362039-c06b2d715385?q=80&w=600&auto=format&fit=crop",bars:[["Vuelo",100],["Metabolismo",100],["Vision",90],["Maniobra",100]],e:"Unico que vuela hacia atras. Corazon de 1200 ppm. Torpor nocturno que ahorra 90%."},
pulpo:{t:"Pulpo — Octopus vulgaris",x:"9 cerebros, 3 corazones y piel camaleonica.",img:"https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?q=80&w=600&auto=format&fit=crop",bars:[["Inteligencia",100],["Camuflaje",100],["Escape",95],["Tacto",100]],e:"2/3 de neuronas en los brazos. Cambia color y textura en 0.3 s. Sin huesos."},
ajolote:{t:"Ajolote — Ambystoma mexicanum",x:"Salamandra que regenera cerebro y corazon.",img:"https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?q=80&w=600&auto=format&fit=crop",bars:[["Regeneracion",100],["Branquias",95],["Resistencia",70],["Adaptacion",90]],e:"Regenera miembros sin cicatriz. Neotenia permanente. Bioindicador de Xochimilco."},
tucan:{t:"Tucan — Ramphastos toco",x:"Ave de pico gigante ligero y termorregulador.",img:"https://images.unsplash.com/photo-1555169062-013468b47731?q=80&w=600&auto=format&fit=crop",bars:[["Pico",100],["Maniobra",75],["Vision",80],["Senal",90]],e:"Pico hueco de espuma osea. Radiador termico ajustable. Pies 2+2 de dosel."}};
function initHeader(){const h=$("#siteHeader"),p=$("#scrollProgress"),t=$("#toTop");addEventListener("scroll",()=>{const y=scrollY;h.classList.toggle("scrolled",y>30);t.classList.toggle("show",y>600);const d=document.documentElement;p.style.width=(y/(d.scrollHeight-innerHeight)*100)+"%"},{passive:true});t.onclick=()=>scrollTo({top:0,behavior:"smooth"});}
function initMenu(){const b=$("#hamburger"),l=$("#navLinks");if(!b||!l)return;b.onclick=()=>{const o=l.classList.toggle("open");b.setAttribute("aria-expanded",o);b.classList.toggle("active",o)};$$(".nav-link").forEach(a=>a.addEventListener("click",()=>{l.classList.remove("open");b.setAttribute("aria-expanded","false");b.classList.remove("active")}));document.addEventListener("click",e=>{if(!l.classList.contains("open"))return;if(e.target.closest("#navLinks,#hamburger"))return;l.classList.remove("open");b.setAttribute("aria-expanded","false")});addEventListener("keydown",e=>{if(e.key==="Escape"){l.classList.remove("open");b.setAttribute("aria-expanded","false")}});}
function initSpy(){const links=$$(".nav-link");const io=new IntersectionObserver(e=>{e.forEach(x=>{if(x.isIntersecting)links.forEach(l=>l.classList.toggle("active",l.getAttribute("href")==="#"+x.target.id))})},{rootMargin:"-40% 0px -55% 0px"});$$("main section[id]").forEach(s=>io.observe(s));}
function initFireflies(){const f=$("#fireflies");if(!f)return;for(let i=0;i<18;i++){const s=document.createElement("span");s.className="firefly";s.style.left=Math.random()*100+"%";s.style.top=Math.random()*100+"%";s.style.animationDelay=(Math.random()*6)+"s";f.appendChild(s);}}
function initSpots(){const tip=$("#spotTip");$$(".hotspot").forEach(h=>h.onclick=()=>{tip.textContent=h.dataset.spot;tip.classList.add("show");clearTimeout(tip._t);tip._t=setTimeout(()=>tip.classList.remove("show"),1800);});}

function initFilter(){const btns=$$(".filter-btn"),cards=$$(".cards-grid .card"),count=$("#filterCount");btns.forEach(b=>b.onclick=()=>{btns.forEach(x=>x.classList.remove("active"));b.classList.add("active");const f=b.dataset.filter;if(b.dataset.biome)setBiome(b.dataset.biome);let n=0;cards.forEach(c=>{const show=f==="all"||c.dataset.group.includes(f);c.classList.toggle("hide",!show);if(show){n++;c.classList.remove("pop");void c.offsetWidth;c.classList.add("pop");}});count.textContent="Mostrando "+n+" de "+cards.length+" especies";});}
function initModal(){const m=$("#speciesModal");const open=k=>{const s=SPECIES[k];if(!s)return;$("#mImg").src=s.img;$("#mImg").alt=s.n;$("#mGroup").textContent=s.g;$("#mName").textContent=s.n;$("#mSci").innerHTML="<em>"+s.s+"</em>";$("#mDesc").textContent=s.d;m.classList.add("open")};const close=()=>m.classList.remove("open");$$("[data-species]").forEach(b=>b.onclick=()=>open(b.dataset.species));$("#modalClose").onclick=close;$("#mAnatomy").onclick=e=>{e.preventDefault();const key=$("#mName").textContent;const k=Object.keys(SPECIES).find(x=>SPECIES[x].n===key);close();document.querySelector("#anatomia").scrollIntoView({behavior:"smooth"});if(k&&window.showAnatomy)setTimeout(()=>window.showAnatomy(k),600);};m.onclick=e=>{if(e.target===m)close()};addEventListener("keydown",e=>{if(e.key==="Escape"){close();$("#galleryModal").classList.remove("open")}});}
function initSystems(){const btns=$$(".sys-btn");btns.forEach(b=>b.onclick=()=>{btns.forEach(x=>x.classList.remove("active"));b.classList.add("active");const s=SYSTEMS[b.dataset.sys];$("#sysName").textContent=s.n;$("#sysDesc").textContent=s.d;$("#sysFun").textContent=s.f;$("#sysSp").textContent=s.s;$("#sysIcon").innerHTML='<i class="fa-solid '+s.i+'"></i>';});}
function initOrgans(){let cur="jaguar";const tabs=$("#speciesTabs"),sel=$("#speciesSelect"),dots=$("#organDots"),btns=$("#organBtns"),tip=$("#organTip"),img=$("#bodyImg");
const keys=Object.keys(SPECIES);
const renderTabs=()=>{tabs.innerHTML="";sel.innerHTML="";keys.forEach(k=>{const s=SPECIES[k];const b=document.createElement("button");b.className="anat-btn"+(k===cur?" active":"");b.dataset.anat=k;b.setAttribute("role","tab");b.textContent=(ANAT_LABEL[k]||s.n);b.onclick=()=>{setSpecies(k);if(window.renderAnatFicha){try{window.renderAnatFicha(k,false)}catch(e){}}};tabs.appendChild(b);const o=document.createElement("option");o.value=k;o.textContent=(ANAT_LABEL[k]||s.n);sel.appendChild(o);});sel.value=cur;};
const setSpot=i=>{const sp=ANATOMY[cur].spots[i];dots.querySelectorAll(".organ-dot").forEach((d,j)=>d.classList.toggle("active",j===i));btns.querySelectorAll(".organ-btn").forEach((d,j)=>d.classList.toggle("active",j===i));$("#organNum").textContent="0"+(i+1);$("#organKicker").textContent="Punto "+(i+1)+" de "+ANATOMY[cur].spots.length+" · "+(ANAT_LABEL[cur]||SPECIES[cur].n);$("#organName").textContent=sp.n;$("#organDesc").textContent=sp.d;$("#organFacts").innerHTML=sp.f.map(f=>"<li>"+f+"</li>").join("");};
const setSpecies=k=>{if(!SPECIES[k]||!ANATOMY[k])return;cur=k;const s=SPECIES[k];tabs.querySelectorAll(".anat-btn").forEach(b=>b.classList.toggle("active",b.dataset.anat===k));sel.value=k;$("#anatTitle").innerHTML=s.n+" — <em>"+s.s+"</em>";img.src=s.img;img.alt=s.n+" para exploración anatómica";dots.innerHTML="";btns.innerHTML="";ANATOMY[k].spots.forEach((sp,i)=>{const d=document.createElement("button");d.className="organ-dot";d.style.left=sp.x;d.style.top=sp.y;d.textContent=(i+1);d.setAttribute("aria-label",sp.n);d.onclick=e=>{e.stopPropagation();setSpot(i);tip.textContent=sp.n+": "+sp.d;tip.classList.add("show");clearTimeout(tip._t);tip._t=setTimeout(()=>tip.classList.remove("show"),2000);};dots.appendChild(d);const b=document.createElement("button");b.className="organ-btn";b.textContent=sp.n;b.onclick=()=>setSpot(i);btns.appendChild(b);});setSpot(0);if(window.gsap)gsap.from("#bodyMap",{y:16,opacity:0,duration:.5,ease:"power2.out"});};
sel.onchange=()=>{setSpecies(sel.value);if(window.renderAnatFicha&&!window._anatLock){window._anatLock=true;try{window.renderAnatFicha(sel.value,false)}catch(e){}window._anatLock=false;}};
window.showAnatomy=(k,sync)=>{setSpecies(k);if(sync!==false&&window.renderAnatFicha&&!window._anatLock){window._anatLock=true;try{window.renderAnatFicha(k,false)}catch(e){}window._anatLock=false;}};
renderTabs();setSpecies("jaguar");}
function initCompare(){const a=$("#selA"),b=$("#selB"),keys=Object.keys(SPECIES);keys.forEach(k=>{a.innerHTML+='<option value="'+k+'">'+SPECIES[k].n+'</option>';b.innerHTML+='<option value="'+k+'">'+SPECIES[k].n+'</option>'});a.value="jaguar";b.value="aguila";const rows=[["Grupo","grupo"],["Habitat","habitat"],["Alimentacion","alim"],["Respiracion","resp"],["Extremidades","ext"],["Temperatura","temp"]];const render=()=>{const A=SPECIES[a.value],B=SPECIES[b.value];$("#cmpImgA").src=A.img;$("#cmpImgA").alt=A.n;$("#cmpNameA").textContent=A.n;$("#cmpSciA").textContent=A.s;$("#cmpImgB").src=B.img;$("#cmpImgB").alt=B.n;$("#cmpNameB").textContent=B.n;$("#cmpSciB").textContent=B.s;$("#thA").textContent=A.n;$("#thB").textContent=B.n;$("#cmpBody").innerHTML=rows.map(r=>'<tr class="'+(A[r[1]]!==B[r[1]]?"diff":"")+'"><td><strong>'+r[0]+'</strong></td><td>'+A[r[1]]+'</td><td>'+B[r[1]]+'</td></tr>').join("");};a.onchange=render;b.onchange=render;$("#swapBtn").onclick=()=>{const t=a.value;a.value=b.value;b.value=t;render();};render();}
function initGallery(){const g=$("#galleryModal");$$(".g-item").forEach(f=>f.onclick=()=>{const img=f.querySelector("img");$("#gImg").src=img.src;$("#gImg").alt=img.alt;$("#gTitle").textContent=f.dataset.title;$("#gDesc").textContent=f.dataset.desc;g.classList.add("open")});$("#gClose").onclick=()=>g.classList.remove("open");g.onclick=e=>{if(e.target===g)g.classList.remove("open")};$("#galleryMore").onclick=()=>{const it=[...$$(".g-item")];it[Math.floor(Math.random()*it.length)].click();};}
function initTheme(){document.body.classList.remove("light");document.body.classList.add("dark");try{localStorage.setItem("anima-theme","dark")}catch(e){}}
function initAnims(){if(window.AOS)AOS.init({duration:800,once:true});if(window.gsap){gsap.from(".hero-copy > *",{y:40,opacity:0,duration:1,stagger:.12});gsap.from(".tilt",{y:50,opacity:0,duration:.8,stagger:.06,scrollTrigger:undefined});}}
/* ===== FONDO VIVO: canvas de particulas por bioma + parallax mouse ===== */
let biome="selva",parts=[],mouse={x:innerWidth/2,y:innerHeight/2},bursts=[];
function setBiome(b){biome=b;document.body.dataset.biome=b;$$(".biome-btn").forEach(x=>x.classList.toggle("active",x.dataset.biome===b));$("#biomeName").textContent=BIOMES[b].n;$("#biomeDesc").textContent=BIOMES[b].d;parts=[];seedParts();}
function seedParts(){const n=biome==="oceano"?70:biome==="cielo"?45:55;for(let i=0;i<n;i++)parts.push(newPart(true));}
function newPart(any){return{x:Math.random()*innerWidth,y:any?Math.random()*innerHeight:innerHeight+20,r:biome==="oceano"?2+Math.random()*5:1+Math.random()*3,vx:(Math.random()-.5)*(biome==="cielo"?1.4:.5),vy:biome==="oceano"?-(.6+Math.random()*1.6):biome==="cielo"?(.4+Math.random()):(.2+Math.random()*.8),a:Math.random()*6.28,col:biome==="oceano"?"46,196,182":biome==="cielo"?"144,190,109":biome==="laguna"?"46,196,182":biome==="sabana"?"233,196,106":"144,190,109"};}
function initBioCanvas(){const c=$("#bioCanvas"),ctx=c.getContext("2d");const fit=()=>{c.width=innerWidth;c.height=innerHeight};fit();addEventListener("resize",fit);addEventListener("mousemove",e=>{mouse.x=e.clientX;mouse.y=e.clientY},{passive:true});seedParts();
c.addEventListener("click",e=>{for(let i=0;i<14;i++)bursts.push({x:e.clientX,y:e.clientY,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4-1,life:1,r:2+Math.random()*3});});
document.addEventListener("click",e=>{if(e.target.closest("button,a,select,.card,.g-item"))return;for(let i=0;i<10;i++)bursts.push({x:e.clientX,y:e.clientY+scrollY*0,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4-1,life:1,r:2+Math.random()*3});});
(function loop(){ctx.clearRect(0,0,c.width,c.height);
const g=ctx.createLinearGradient(0,0,0,c.height);
if(biome==="oceano"){g.addColorStop(0,"rgba(8,40,50,.55)");g.addColorStop(1,"rgba(11,31,22,.2)");}
else if(biome==="cielo"){g.addColorStop(0,"rgba(60,120,90,.25)");g.addColorStop(1,"rgba(11,31,22,.05)");}
else if(biome==="laguna"){g.addColorStop(0,"rgba(20,80,70,.4)");g.addColorStop(1,"rgba(11,31,22,.1)");}
else if(biome==="sabana"){g.addColorStop(0,"rgba(120,70,20,.3)");g.addColorStop(1,"rgba(11,31,22,.05)");}
else{g.addColorStop(0,"rgba(26,77,46,.4)");g.addColorStop(1,"rgba(11,31,22,.05)");}
ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);
parts.forEach(p=>{p.a+=.02;p.x+=p.vx+Math.sin(p.a)*.4+(mouse.x-innerWidth/2)*.0006;p.y+=biome==="oceano"||biome==="sabana"?p.vy:-Math.abs(p.vy)*.4;
if(p.y<-20)p.y=innerHeight+20;if(p.y>innerHeight+20)p.y=-20;if(p.x<-20)p.x=innerWidth+20;if(p.x>innerWidth+20)p.x=-20;
ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fillStyle=`rgba(${p.col},.7)`;ctx.fill();
if(biome==="oceano"){ctx.strokeStyle=`rgba(${p.col},.25)`;ctx.stroke();}});
bursts=bursts.filter(b=>b.life>0);bursts.forEach(b=>{b.x+=b.vx;b.y+=b.vy;b.life-=.02;ctx.beginPath();ctx.arc(b.x,b.y,b.r*b.life,0,7);ctx.fillStyle=`rgba(233,196,106,${b.life})`;ctx.fill();});
requestAnimationFrame(loop);})();
// distribuir hierba / burbujas / hojas / ondas
$$(".blade").forEach((b,i)=>{b.style.left=(i*8+Math.random()*4)+"%";b.style.height=(70+Math.random()*90)+"px";b.style.animationDelay=(Math.random()*3)+"s";});
$$(".bubble").forEach((b,i)=>{b.style.left=(5+i*12+Math.random()*5)+"%";const s=10+Math.random()*26;b.style.width=b.style.height=s+"px";b.style.animationDelay=(Math.random()*7)+"s";b.style.animationDuration=(5+Math.random()*5)+"s";});
$$(".leaf").forEach((b,i)=>{b.style.left=(i*16+Math.random()*8)+"%";b.style.animationDelay=(Math.random()*8)+"s";});
$$(".ripple").forEach((b,i)=>{b.style.left=(15+i*30)+"%";b.style.animationDelay=(i*1.3)+"s";});
$$(".fire").forEach((b,i)=>{b.style.left=(10+i*20+Math.random()*6)+"%";b.style.animationDelay=(Math.random()*5)+"s";});
$$(".biome-btn").forEach(b=>b.onclick=()=>setBiome(b.dataset.biome));}
/* ===== tilt 3D + contadores + anatomia multi ===== */
function initTilt(){$$(".tilt").forEach(card=>{card.addEventListener("mousemove",e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*10}deg) rotateX(${-y*10}deg) translateY(-8px)`;});card.addEventListener("mouseleave",()=>card.style.transform="");});}
function initCounters(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=+el.dataset.count;let v=0;const t=setInterval(()=>{v+=1;el.textContent=v;if(v>=end)clearInterval(t)},80);io.unobserve(el)}));$$("[data-count]").forEach(el=>io.observe(el));}
function initMultiAnat(){const box=$("#anatTabs");if(!box)return;const keys=Object.keys(SPECIES);const render=(k,sync)=>{if(!SPECIES[k])return;const s=SPECIES[k],a=ANAT[k]||ANAT.jaguar;box.querySelectorAll(".anat-btn").forEach(b=>b.classList.toggle("active",b.dataset.anat===k));$("#anatImg").src=s.img;$("#anatImg").alt="Anatomía de "+s.n;$("#anatName").textContent=s.n;$("#anatText").textContent=s.d+" "+a.x;$("#anatExtra").innerHTML="<strong>Adaptación clave:</strong> "+a.e;$("#anatBars").innerHTML=a.bars.map(b=>'<div class="bar-row"><span>'+b[0]+'</span><div class="bar"><i data-w="'+b[1]+'"></i></div><strong>'+b[1]+'</strong></div>').join("");requestAnimationFrame(()=>requestAnimationFrame(()=>$$("#anatBars .bar i").forEach(i=>i.style.width=i.dataset.w+"%")));if(window.gsap)gsap.from("#anatDetail",{y:24,opacity:0,duration:.6,ease:"power2.out"});if(sync!==false&&window.showAnatomy&&!window._anatLock){window._anatLock=true;try{window.showAnatomy(k)}catch(e){}window._anatLock=false;}};box.innerHTML="";keys.forEach(k=>{const b=document.createElement("button");b.className="anat-btn";b.dataset.anat=k;b.textContent=SPECIES[k].n;b.onclick=()=>render(k);box.appendChild(b);});window.renderAnatFicha=render;render("jaguar",false);}
document.addEventListener("DOMContentLoaded",()=>{initHeader();initMenu();initSpy();initFireflies();initSpots();initFilter();initModal();initSystems();initOrgans();initCompare();initGallery();initTheme();initAnims();initBioCanvas();initTilt();initCounters();initMultiAnat();setBiome("selva");});